development:
  auth_tokens:
    global: "SuperToken"
  stripe:
    public_key: "pk_test_UBER_SECRET"
    secret_key: "sk_test_UBER_SECRET"
  notifier:
    slack:
      account: 'rgsoc-test'
      token:   'UBER_TOKEN'
      channel: 'bestchannelever'

test:
  auth_tokens:
    global: "SuperToken"
  stripe:
    public_key: "pk_test_UBER_SECRET"
    secret_key: "sk_test_UBER_SECRET"
  notifier:
    slack:
      account: 'rgsoc-test'
      token:   'UBER_TOKEN'
      channel: 'bestchannelever'
