development:
  stripe:
    public_key: "pk_test_UBER_SECRET"
    secret_key: "sk_test_UBER_SECRET"
  slack:
    account: 'rgsoc-test'
    token:   'UBER_TOKEN'
    channel: 'bestchannelever'

test:
  stripe:
    public_key: "pk_test_UBER_SECRET"
    secret_key: "sk_test_UBER_SECRET"
  slack:
    account: 'rgsoc-test'
    token:   'UBER_TOKEN'
    channel: 'bestchannelever'
